#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os, sys
from os.path import dirname, lexists, join as pjoin

prefix = dirname(dirname(sys.argv[0]))
libdir = pjoin(prefix,'share','subvirc')
if prefix == '' or not lexists(libdir):
    libdir = os.getcwd()
sys.path.insert(1, libdir)

import irc
if __name__ == '__main__':
    irc.main()
