#!/usr/bin/env ruby
$stdin.readline # don't care about the user.
line = $stdin.readline
args = line.split

if args.length == 0
    alts = %w{heads tails}
elsif line =~ /\bor\b/
    alts = line.split(/\bor\b/)
    alts[alts.length-1].gsub!(/\?$/,'')
else
    alts = %w{yes no}
end
reply = alts[rand(alts.length)].strip

puts reply
