#!/usr/bin/env python3

import sys
from random import randrange

def roll(count, sides):
    try:
        count = 1 if count == '' else int(count)
        sides = 6 if sides == '' else int(sides)
    except ValueError:
        return "wtf, that's not a number"

    if sides < 2:
        return '%s-sided die not available in this universe' % sides
    if count > 10:
        count = 10

    rands = [randrange(1,sides+1) for i in range(count)]
    if count > 1:
        result = "%sd%s = %s (%s)" % (count, sides, sum(rands), " + ".join([str(i) for i in rands]))
    else:
        result = "%sd%s = " % (count,sides) + str(rands[0])
    return result

sys.stdin.readline() # don't care about username etc.
args = sys.stdin.readline().split()
if len(args) == 0:
    args = ['1d6']
result = []
for word in args:
    (count, sides) = word.split('d',1)
    result.append(roll(count, sides))
if len(result) > 0:
    print('; '.join(result))
